import './globals.css'
import { Inter } from 'next/font/google'
import {SessionProvider, SolidContextProvider} from './context-providers'
import Nav from './components/nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props: {
  children: React.ReactNode,
  authModal: React.ReactNode,
}) {
  return (
    <html lang="en">
      <SessionProvider>
        <SolidContextProvider>
          <body className='flex flex-col h-screen'>
            <Nav />
            <div className='h-full'>
              {props.children}
              {props.authModal}
            </div>
          </body>
        </SolidContextProvider>
      </SessionProvider>
    </html>
  )
}
